[package]
version = "0.3.0"

title = "fredericl ndi experimentation"
description = "Python extension to connect dynamic textures to ndi feed(s)"
authors = ["Frederic Lestage"]

readme  = "docs/README.md"
changelog = "docs/CHANGELOG.md"
repository = "https://gitlab.com/momentfactory/products/xagora/omniverse/kit-exts-ndi/"

category = "NDI"
keywords = ["kit", "ndi", "dynamic texture"]

preview_image = "data/preview.png"
icon = "data/icon.png"

[dependencies]
"omni.kit.uiapp" = {}


[[python.module]]
name = "fredericl.ndi.experimentation"

[python.pipapi]
requirements = [
    "opencv-python",
    "ndi-python"
]
use_online_index = true
