[package]
version = "0.5.0"

title = "Omniverse NDI® extension"
description = "The NDI® Omniverse extension allows you to use live video feeds as textures in your stages."
authors = ["Moment Factory","Frederic Lestage"]

readme  = "docs/README.md"
changelog = "docs/CHANGELOG.md"
repository = "https://gitlab.com/momentfactory/products/xagora/omniverse/kit-exts-ndi/"

category = "Services"
keywords = ["NDI", "texture", "live-feed", "video", "broadcast", "audiovisual", "realtime"]

preview_image = "data/preview.png"
icon = "data/icon.png"

[dependencies]
"omni.kit.uiapp" = {}


[[python.module]]
name = "mf.ov.ndi"

[python.pipapi]
requirements = [
    "ndi-python"
]
use_online_index = true
